### ISSUE TITLE
Make sure that the reproducible-build-maven-plugin is the last plugin in the plugins list

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/project-keeper#132]
## Problem

Maven plugins that belong to the same execution phase are executed in the order they are places in the pom file. The problem here is if we place the source plugin after the reproducible-build-maven-plugin, the source jar is not stripped because it's generated after the reproducible-build-maven-plugin runs.

## Possible Solution

Validate that the reproducible-build-maven-plugin  is the last plugin in the plugins list.

**Comment by jakobbraun** [comment]
I don't really like to have the rule that it must be the last plugin in the list, since:
* It's a too hard criteria – It will produce validation findings even though everything is ok
* It's critical if we have more plugins that need to be the last one

Ideas: 
* Add a weight for different plugins: For plugins with same order, weight is irrelevant
* Only validate weight in the scope of execution phase
* 
On the other hand, maybe it would make sense to order our plugins by execution phase...
