### ISSUE TITLE
Review Release Droid Requirements 

### ISSUE THREAD

**Issue by ckunki** [exasol/project-keeper#543]
PK 4.2.0 introduces automated releases and hence may replace [Release Droid](https://github.com/exasol/release-droid/). However, we did not do a thorough review of the original requirements set up for Release Droid. 

The current ticket requests to review these requirements to make sure to not have skipped an important feature during the migration. 

The outcome should be a list, which each entry being a requirement or design entry of RD req spec on any level. So it is OK to assign a single rating to a whole section, for example. 

Each entry should have one of the following ratings

* implemented
* rejected + rationale 
* not implemented, yet, but should be planned to be implemented in future

**Comment by kaklakariada** [comment]
## [Requirements from RD](https://github.com/exasol/release-droid/blob/main/doc/system_requirements.md)

### Release Validation
RD lets Software Developers and Integrators check whether all conditions for a release are fulfilled.
* Implemented by `verify-release` mode ✅ 

### Release Automation
RD generates releases without human interaction.
* ✅ 

### Maven Support
RD support releases based on Apache Maven projects.
* ✅ 

### GitHub Support
RD supports releasing on GitHub.
* ✅ 

### Exasol Community Portal Support
RD supports releasing on the [Exasol Community Portal](https://community.exasol.com/).
* 🛑 Not necessary any more

### Golang Support
RD supports releasing projects with modules using programming language `go`.
* ❗ Will be implemented in https://github.com/exasol/project-keeper/issues/556

### Report
RD writes a report that summarizes all steps and their results.
* 🛑 Not required any more

### Estimation and Progress Display
RD estimates the duration of the release process and displays progress during release process.
* 🛑 Not required any more

### Release Guide
RD supports developers to aggregate data describing the release and for announcing it to the defined channels.
* ❓

### Validation Report
RD creates a validation report containing all successful and failed validations.
* ✅ The `release.yml` workflow generates a Workflow summary with the successful and failed steps

### Release Estimation and Progress Display
RD estimates the duration of the release process and displays progress during release process.
* ❓ 

### Users Can Set Git Branch for Validation
`req~users-can-set-git-branch-for-validation~1`
Users can set a branch to perform a validation on.
* ✅ Users can run PK `verify-release` mode on any branch

### Run Tests Only Once
RD runs all project's tests only once. This means RD will not run the tests again in case the release was not finished and no changes were made on the project, and a new release command is triggered.
* ✅ PK `release.yml` verifies that `ci-build.yml` ran on `main` branch for the current commit successfully. So running tests again is not required.

##### Validate Mandatory Directory Tree Elements
RD validates mandatory directory tree elements.
* ✅ Check is included in PK `verify-release` mode

##### Stopping the Release on Failed Step Validation
RD stops a release if a step's validation fails.
* ✅ `relase.yml` verifies that `ci-build.yml` succeeded

##### Stopping the Release in Case of Version Conflicts in the Project Sources
RD stops a release if there is detects one of the version conflicts listed below:
* Version number of the current release was already used in a previous release.
* Version numbering has a gap (e.g it jumped from 1.1.0 to 3.0.0)
* ✅ Check is included in PK `verify-release` mode

##### Releasing on Maven Central Repository
RD can create a Maven Central Repository release.
* ✅ included in `relase.yml`

##### Detect Current Version From Maven POM
RD can derive the current version from the project's POM file.
* ✅ Check is included in PK `verify-release` mode

##### Detect Deliverables in a Maven Project
RD detects which files in a Maven Project are deliverables.
* ✅ Included in PK `verify-release` mode & `relase.yml`

##### Releasing on GitHub
RD can create a GitHub release.
* ✅ implemented in `relase.yml`

##### Validating the Release Date
RD validates the release date during validation.
* ✅ Check is included in PK `verify-release` mode

##### Automatically Modifying Release Date
**Removed** We removed this feature because with branch protection it's not possible any more to update files directly on the `main` branch. This feature is replaced by `req~validating-release-date~1`.
* 🛑 Not implemented, maybe later

##### GitHub Release Description From Release Letter
RD copies the release letter into the release description of a GitHub release.
* ✅ Included in PK `verify-release` mode & `relase.yml`

##### GitHub Release Title from Release Letter
RD extracts the GitHub release title from the release letter.
* ✅ Included in PK `verify-release` mode & `relase.yml`

##### Validating GitHub Issue Ticket Numbers
RD validates that the issue ticket numbers mentioned in the release letter exist.
* ✅ Included in PK `verify-release` mode

##### Validating That GitHub Issues are Closed
RD validates that the issue ticket numbers mentioned in the release letter are all closed.
* ✅ Included in PK `verify-release` mode

##### Attaching Deliverables to a GitHub Release
RD attaches the deliverables to a GitHub release.
* ✅ Included in PK `verify-release` mode & `relase.yml`

##### Creating Additional Tags
For projects with modules using programming language `go` RD creates appropriate git tags.
* ❗ Will be implemented in https://github.com/exasol/project-keeper/issues/556

**Comment by ckunki** [comment]
Review approved :white_check_mark:
